### ISSUE TITLE
Is OUTPUT required for anthing

### ISSUE THREAD

**Issue by gvenzl** [gvenzl/setup-oracle-free#2]
Hey @aalmiray,

I spotted what appears to be an unused variable in the shell script called `OUTPUT`: https://github.com/gvenzl/setup-oracle-free/blob/dev/setup-oracledb.sh#L147

Is that any kind of "magic" GHA variable that is expected to be set, or just a leftover of something?

**Comment by aalmiray** [comment]
Yes, I think is a leftover of the time when I thought I could grab the random password from the container's output. Which would work if the process was not detached 😅

The command invocation must proceed but the variable can be removed.

**Comment by gvenzl** [comment]
Fixed
